PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS user_device (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   suid BLOB NOT NULL,
   key BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS nickname (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   suid BLOB NOT NULL,
   name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS team (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    suid BLOB NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    suid BLOB NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_team (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    suid BLOB NOT NULL,
    app_id INTEGER NOT NULL,
    team_id INTEGER NOT NULL,
    FOREIGN KEY (app_id) REFERENCES app(id) ON DELETE CASCADE,
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cloud (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    protocol TEXT NOT NULL,
    url TEXT NOT NULL
);
